spring:
  application:
    name: checkin-service

server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.1:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
  healthcheck:
    enabled: true
