spring:
  application:
    name: search-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      #defaultZone: http://172.17.0.1:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
  healthcheck:
    enabled: true

originairports:
  shutdown: JFK

