spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brajdev/config-server

server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.1:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
  healthcheck:
    enabled: true